export default {
  '051d5d92': [() => import(/* webpackChunkName: '051d5d92' */ 'C:\\Users\\Rafa\\Documents\\projetos pessoais\\Portifolio-Brandao-main\\.docusaurus\\docusaurus-plugin-content-pages\\default\\plugin-route-context-module-100.json'), 'C:\\Users\\Rafa\\Documents\\projetos pessoais\\Portifolio-Brandao-main\\.docusaurus\\docusaurus-plugin-content-pages\\default\\plugin-route-context-module-100.json', require.resolveWeak('C:\\Users\\Rafa\\Documents\\projetos pessoais\\Portifolio-Brandao-main\\.docusaurus\\docusaurus-plugin-content-pages\\default\\plugin-route-context-module-100.json')],
  '17896441': [() => import(/* webpackChunkName: '17896441' */ '@theme/DocItem'), '@theme/DocItem', require.resolveWeak('@theme/DocItem')],
  '1be78505': [() => import(/* webpackChunkName: '1be78505' */ '@theme/DocPage'), '@theme/DocPage', require.resolveWeak('@theme/DocPage')],
  '595ed226': [() => import(/* webpackChunkName: '595ed226' */ 'C:\\Users\\Rafa\\Documents\\projetos pessoais\\Portifolio-Brandao-main\\.docusaurus\\docusaurus-plugin-content-docs\\default\\plugin-route-context-module-100.json'), 'C:\\Users\\Rafa\\Documents\\projetos pessoais\\Portifolio-Brandao-main\\.docusaurus\\docusaurus-plugin-content-docs\\default\\plugin-route-context-module-100.json', require.resolveWeak('C:\\Users\\Rafa\\Documents\\projetos pessoais\\Portifolio-Brandao-main\\.docusaurus\\docusaurus-plugin-content-docs\\default\\plugin-route-context-module-100.json')],
  '5e9f5e1a': [() => import(/* webpackChunkName: '5e9f5e1a' */ '@generated/docusaurus.config'), '@generated/docusaurus.config', require.resolveWeak('@generated/docusaurus.config')],
  '616665f6': [() => import(/* webpackChunkName: '616665f6' */ '@site/docs/doc3.md'), '@site/docs/doc3.md', require.resolveWeak('@site/docs/doc3.md')],
  '935f2afb': [() => import(/* webpackChunkName: '935f2afb' */ '~docs/default/version-current-metadata-prop-751.json'), '~docs/default/version-current-metadata-prop-751.json', require.resolveWeak('~docs/default/version-current-metadata-prop-751.json')],
  'b2f90839': [() => import(/* webpackChunkName: 'b2f90839' */ '@site/docs/doc1.md'), '@site/docs/doc1.md', require.resolveWeak('@site/docs/doc1.md')],
  'c4f5d8e4': [() => import(/* webpackChunkName: 'c4f5d8e4' */ '@site/src/pages/index.js'), '@site/src/pages/index.js', require.resolveWeak('@site/src/pages/index.js')],
  'ce3e42ad': [() => import(/* webpackChunkName: 'ce3e42ad' */ '@site/docs/mdx.md'), '@site/docs/mdx.md', require.resolveWeak('@site/docs/mdx.md')],
  'df361e2b': [() => import(/* webpackChunkName: 'df361e2b' */ '@site/docs/doc2.md'), '@site/docs/doc2.md', require.resolveWeak('@site/docs/doc2.md')],};
